### ISSUE TITLE
youtube-dl update

### ISSUE THREAD

**Issue by TGraham04** [jac241/power_hour_creator#57]
Hey i think the youtube-dl needs an update for the exe i love using this and for the life of me cant get it to build on my  system so if you update and create a new exe you will be my favorite person.

**Comment by gregums88** [comment]
Looks like they need to update to this new Youtube-dl coding

https://github.com/ytdl-org/youtube-dl/commit/00eb865b3c8002f47e73706b54f58feaee0b0ac2

**Comment by jac241** [comment]
I'll get it done later today if that works for you. Thanks appreciate it.

**Comment by jac241** [comment]
https://github.com/jac241/power_hour_creator/releases/tag/v1.0.0-beta.2020-03-24

Give it a shot. One day I'll make it auto-update youtube-dl...

**Comment by gregums88** [comment]
Works! Awesome, thank you!! Hope you are healthy and safe during these crazy times.

**Comment by TGraham04** [comment]
Thank you so much!
