### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by gregums88** [jac241/power_hour_creator#60]
Having a Youtube DL error again. Appreciate all your work through these crazy times.

Thanks!

**Comment by jac241** [comment]
Thanks for letting me know. I'll upload a new version this afternoon or
evening.

**Comment by gregums88** [comment]
I was able to add the youtube links in now but get this error after hitting Create Power Hour. "Error occurred while downloading media file: ERROR: unable to download video data: HTTP Error 403: Forbidden" 

Thanks!

**Comment by jac241** [comment]
Searching the Youtube-DL 403 forbidden error got me this:

![image](https://user-images.githubusercontent.com/3792672/80849603-dbd28500-8be5-11ea-80a9-70f7f4f9d911.png)

Maybe try deleting that folder. More here - https://www.reddit.com/r/youtubedl/comments/g46pqc/impossible_to_download_some_videos_http_error_403/

**Comment by thegodofcheese** [comment]
now, after deleting that folder, i get this error:

Error occurred while downloading media file: ERROR: No video formats found; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.

**Comment by thegodofcheese** [comment]
for what it's worth, i was able to get past this by uninstalling, deleting all cache files, and deleting all files from the program files (x86) directory as well. works fine after reinstallation.

**Comment by jac241** [comment]
I've uploaded a new release with the latest youtube-dl. Let me know if it works thanks.

https://github.com/jac241/power_hour_creator/releases/tag/v1.0.0-beta.2020.05.08

**Comment by thegodofcheese** [comment]
Perfect! Thank you sir! We greatly enjoy power hours with our friends, and since we can't be near them in this quarantine life, video chatting while partaking in one of these together is perfect. Cheers!

**Comment by jac241** [comment]
Glad you like it. I'm just surprised people ended up finding this random
GitHub repo and app haha.

**Comment by sixersfan105** [comment]
I just came across this awesome application today, but unfortunately, I have gotten the download error on every single YouTube URL I have tried to input into Power Hour Creator. I am using the latest version, v.1.0.0-beta.2020.05.08. Would you be able to update it again? I'm planning on doing a power hour via Zoom with some friends on Friday and your application is definitely the best option for us. Thank you!!

**Comment by thegodofcheese** [comment]
i think youtube.dl needs updating again. getting a download error once more.

**Comment by thegodofcheese** [comment]
any chance we can get this updated with the new youtube.dl? if i knew what needed to be done i could try and download the source and recompile but sadly i'm kind of at a loss and it's not working anymore :(
