### ISSUE TITLE
YouTube Download Error with v.1.0.0-beta.2020.05.08

### ISSUE THREAD

**Issue by sixersfan105** [jac241/power_hour_creator#61]
I just came across this awesome application today, but unfortunately, I have gotten the download error on every single YouTube URL I have tried to input into Power Hour Creator. I'm on a Mac using the newest version of the application, v.1.0.0-beta.2020.05.08. Would you be able to update it again? I'm planning on doing a power hour via Zoom with some friends on Friday and your application is definitely the best option for us. Thank you!!

**Comment by jac241** [comment]
Hey. 2020-05-08 is the latest youtube-dl and it is working on my mac so try deleting the folder /Users/[Your username]/.cache/youtube-dl/ and then retry. Sometimes you need to clear the youtube-dl cache for it to work. Let me know.

**Comment by sixersfan105** [comment]
Doesn't appear as though that folder exists on my end. Oh do I need to install youtube-dl and Python on my computer to successfully use your program?

**Comment by jac241** [comment]
You don't need to download those, power hour creator includes versions to use. What error specifically is it giving you? Also, what version of MacOS are you on?

In the application's menu, can you go to Help --> Show logs, and copy the last bunch of lines out of that file, or attach and upload the file here in github? Thanks, sorry it's not working for you.

**Comment by sixersfan105** [comment]
Ok cool. I'm using 10.13.6 High Sierra. The error I'm getting, showing at the bottom of the screen, is as follows: 
**Error downloading "https://www.youtube.com/watch?v=K715ZeVVoCA": ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)>(caused by URLError(SSLError(1, '[SSL:CERTIFICATE_VERIFY_FAILED] certificate veri**... and then it cuts off from there

Here's the log:

**05-25 12:28 power_hour_creator.boot INFO     Connecting to DB: /Users/ben/Library/Application Support/Power Hour Creator/production.db
05-25 12:28 power_hour_creator.boot INFO     Migrating DB to level 1
05-25 12:28 power_hour_creator.boot INFO     Successfully migrated DB to level 1
05-25 12:28 power_hour_creator.boot INFO     Migrating DB to level 2
05-25 12:28 power_hour_creator.boot INFO     Successfully migrated DB to level 2
05-25 12:28 power_hour_creator.boot INFO     Migrating DB to level 3
05-25 12:28 power_hour_creator.boot INFO     Successfully migrated DB to level 3
05-25 12:28 power_hour_creator.boot INFO     Migrating DB to level 4
05-25 12:28 power_hour_creator.boot INFO     Successfully migrated DB to level 4
05-25 12:28 power_hour_creator.power_hour_creator INFO     Launching GUI
05-25 12:28 power_hour_creator.power_hour_creator INFO     Showing main window
05-25 12:52 power_hour_creator.boot INFO     Connecting to DB: /Users/ben/Library/Application Support/Power Hour Creator/production.db
05-25 12:52 power_hour_creator.power_hour_creator INFO     Launching GUI
05-25 12:52 power_hour_creator.power_hour_creator INFO     Showing main window
05-25 13:23 power_hour_creator.boot INFO     Connecting to DB: /Users/ben/Library/Application Support/Power Hour Creator/production.db
05-25 13:23 power_hour_creator.power_hour_creator INFO     Launching GUI
05-25 13:23 power_hour_creator.power_hour_creator INFO     Showing main window
05-25 14:36 power_hour_creator.boot INFO     Connecting to DB: /Users/ben/Library/Application Support/Power Hour Creator/production.db
05-25 14:36 power_hour_creator.power_hour_creator INFO     Launching GUI
05-25 14:36 power_hour_creator.power_hour_creator INFO     Showing main window
05-25 14:37 power_hour_creator.boot INFO     Connecting to DB: /Users/ben/Library/Application Support/Power Hour Creator/production.db
05-25 14:37 power_hour_creator.power_hour_creator INFO     Launching GUI
05-25 14:37 power_hour_creator.power_hour_creator INFO     Showing main window**

**Comment by jac241** [comment]
Can you give this version a shot - https://github.com/jac241/power_hour_creator/releases/tag/v1.0.0-beta.2020.05.08-SSL-fix

There was an issue with python not including an SSL certificate that is needed to reach out to https sites from youtube-dl. Hopefully this fixes it, but let me know if it does not.

**Comment by sixersfan105** [comment]
Works like a charm! Thanks so much for the quick fix!

**Comment by jac241** [comment]
Awesome glad to hear it! I was gonna be a little worried if that fix didn't work out...
