### ISSUE TITLE
Power Hour Creator

### ISSUE THREAD

**Issue by kennypowers508** [jac241/power_hour_creator#63]
I would like to make a power hour playlist with music videos from YouTube (and pick the start times), but I do not have any coding experience. I see in the description that I will need a variety of programs to create the power hour, but is there any way that you could put this into simple terms for me to understand? I'm not sure what to download and how. I appreciate what you've created and I'm sorry that I do not understand this yet.

**Comment by jac241** [comment]
Updated

https://github.com/jac241/power_hour_creator/releases/tag/v1.0.0-beta.2020.12.14
